---
:source:
  :path: test
  :file: test_e.c
:successes:
- :test: test_BasicTryDoesNothingIfNoThrow
  :line: 17
  :message: ''
  :unity_test_time: 0
- :test: test_BasicThrowAndCatch
  :line: 38
  :message: ''
  :unity_test_time: 0
- :test: test_BasicThrowAndCatch_WithMiniSyntax
  :line: 57
  :message: ''
  :unity_test_time: 0
- :test: test_VerifyVolatilesSurviveThrowAndCatch
  :line: 77
  :message: ''
  :unity_test_time: 0
- :test: test_ThrowFromASubFunctionAndCatchInRootFunc
  :line: 106
  :message: ''
  :unity_test_time: 0
- :test: test_ThrowAndCatchFromASubFunctionAndRethrowToCatchInRootFunc
  :line: 149
  :message: ''
  :unity_test_time: 0
- :test: test_ThrowAndCatchFromASubFunctionAndNoRethrowToCatchInRootFunc
  :line: 168
  :message: ''
  :unity_test_time: 0
- :test: test_ThrowAnErrorThenEnterATryBlockFromWithinCatch_VerifyThisDoesntCorruptExceptionId
  :line: 185
  :message: ''
  :unity_test_time: 0
- :test: test_ThrowAnErrorThenEnterATryBlockFromWithinCatch_VerifyThatEachExceptionIdIndependent
  :line: 203
  :message: ''
  :unity_test_time: 0
- :test: test_CanHaveMultipleTryBlocksInASingleFunction
  :line: 230
  :message: ''
  :unity_test_time: 0
- :test: test_CanHaveNestedTryBlocksInASingleFunction_ThrowInside
  :line: 255
  :message: ''
  :unity_test_time: 0
- :test: test_CanHaveNestedTryBlocksInASingleFunction_ThrowOutside
  :line: 282
  :message: ''
  :unity_test_time: 0
- :test: test_AbilityToExitTryWithoutThrowingAnError
  :line: 344
  :message: ''
  :unity_test_time: 0
- :test: test_AbilityToExitTryWillOnlyExitOneLevel
  :line: 365
  :message: ''
  :unity_test_time: 0
:failures:
- :test: test_AThrowWithoutATryCatchWillUseDefaultHandlerIfSpecified
  :line: 317
  :message: Expected FALSE Was TRUE
  :unity_test_time: 0
- :test: test_AThrowWithoutOutsideATryCatchWillUseDefaultHandlerEvenAfterTryCatch
  :line: 340
  :message: Expected FALSE Was TRUE
  :unity_test_time: 0
:ignores: []
:counts:
  :total: 16
  :passed: 14
  :failed: 2
  :ignored: 0
:stdout: []
:time: 0.01785569999992731
